### ISSUE TITLE
'Variation' page feedback

### ISSUE THREAD

**Issue by mbrush** [ga4gh/vr-spec#108]
https://vr-spec.readthedocs.io/en/latest/specification/terms_and_model/variation.html

Just minor comments/questions here:

1. For completeness/consistency, I would consider including an IM table for the Variation class - even if just an id and type.
  
2. Do you intend to include non-sequence variation  in the planned Variation concepts here: https://vr-spec.readthedocs.io/en/latest/appendices/future_plans.html#planned-variation?

**Comment by larrybabb** [comment]
@mbrush responses to the 2 items above...

1. I wasn't sure about adding IM tables for the superclasses. It didn't seem like the way we wanted to go in the VMC so we've continued in the same manner in the VR-Spec. I believe the argument is that we should only describe the IM table for the concrete concepts not the abstract. But we can reference the fact that the concepts are derived from common items in the abstract. That is why you see the Variation ID; and Variation type; prefixes in the descriptions of all the id and type fields in the Variation subclasses.  I may be off on this, but I'm waiting for the primary author to return to provide some rationale to which approach is in line with the overall plan. 

2. we do have a section set aside for non-sequence variation. I've left it for someone else to write up as I'm not confident on how to describe it.
It can be found [here](https://vr-spec.readthedocs.io/en/latest/appendices/future_plans.html#non-sequence-variation).  Since it is not so obvious to find we may want to add some additional structure to the Planned Concepts section to visualize the subheadings better in the sidebar. I'll add a ticket to do so.

**Comment by reece** [comment]
I agree with Larry re: 1, and I dropped the non-sequence variation from future plans because we don't really know what to say there. Closing this issue.
