### ISSUE TITLE
Examples section

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#118]
We should have a top-level section of examples for how various variant types are represented in VR spec. SNVs, MNVs, Indels should be easy, and we have Inversions as a special case of insertion-deletion event.

Creating this issue in response to discussion in related thread: https://github.com/ga4gh/vr-python/issues/29

# To do
- [ ] #120
- [ ] #121 
- [ ] #131  
- [ ] excerpt for computed id section (suggested by @mbrush)

**Comment by larrybabb** [comment]
See issues #120 and #121 which could potentially be subsumed by this fix if it were to happen before the review of RC1 is underway.

Also note that there are no Example sections for Allele and Text in the spec which seems like an oversight since there are singular examples in SimpleInterval and Location.

**Comment by reece** [comment]
- [ ] #120
- [ ] #121 
- [ ] #131
