### ISSUE TITLE
Implement ChromosomeLocation class

### ISSUE THREAD

**Issue by reece** [ga4gh/vr-spec#181]

**Comment by rrfreimuth** [comment]
Please share any draft ideas related to these classes.  If that request is premature, I'll wait for the topic to come up on a VR call. :-)

In the meantime, here are a couple of random thoughts about these entities (recognizing that my assumption about what they are intended to mean might be incorrect):

1. CytobandLocation is similar to SequenceLocation, but it uses a different unit of measure and it has a much more coarse level of precision (obviously, it is not at the nucleotide level).  We have modeled this concept in the HL7 CG Info Modeling group (see slide 22 or so [here](https://drive.google.com/file/d/1cwk5-AF35e1rIuFZx9Eh9yMdT9_YxVwi/view?usp=sharing)) and I'd be happy to discuss our approach.
2. I consider GeneLocation to be a specialization of a SequenceFeatureLocation, as Gene is a type of SequenceFeature (see slides 55+ in the link above).  The model we built follows the Allele pattern: a SequenceFeatureLocation is simply a SequenceFeature + a Location (which is an Interval + Sequence).  I'm trying to keep the models in HL7 and GA4GH harmonized as much as possible, so it is important to work through this if our intended semantics differ.
3. The mapping of either CytobandLocation or GeneLocation to base-level coordinates is, in my mind, an _assertion_ that is based on additional data: a mapping table that translates between those frames of reference.  Since that mapping table can vary, it must be included (by reference) in any such assertion so the results can be placed into context.  The point is that any of those 3 types of Location can stand on their own, but translations among them require additional data and result in assertions that change the nature of (or at least complicate) the statements being made.

**Comment by reece** [comment]
Another PDF from Bob: https://drive.google.com/file/d/1xLyKnwtHXvKjRiKo03utkCUMgR8wLOYB/view

**Comment by reece** [comment]
Also see comments in #44, which I'll now close so that this issue consolidates discussion.
