### ISSUE TITLE
Clarify normalization of reference Alleles

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#193]
We should talk about normalized reference Alleles. Our normalization routine trims reference-matching sequence, and we do not discuss what happens in edge cases where the `SeqenceState.sequence` value precisely matches the `sequence` extracted from the `SequenceLocation`. To illustrate:

Scenario 1:
`Ref: AACTAA` (interbase coordinates [0,6] of SQ.123)
`Alt: AACTAA`
Computed ID: `VA.abc123`

Scenario 2:
`Ref: ACTAA` (interbase coordinates [1,6] of SQ.123)
`Alt: ACTAA`
Computed ID: `VA.xyz789` (does not match Scenario 1)

Scenario 3:
`Ref: AACTAA` (interbase coordinates [0,6] of SQ.123)
`Alt: ATCTAA`
Computed ID: `VA.def456`

Scenario 4:
`Ref: ACTAA` (interbase coordinates [1,6] of SQ.123)
`Alt: TCTAA`
Computed ID: `VA.def456` (does match Scenario 3)

In the above, when dealing with a reference-matching `sequence`, each `Allele` returns a different identifier based upon choice of interval start. (See **Scenario 1** compared to **Scenario 2**)

However, if there are reference-differing residues in `sequence`, each `Allele` returns the same identifier regardless of choice of interval start. (See **Scenario 3** compared to **Scenario 4**).

Whether or not this merits attention is unclear, but the ramifications are that differences between interval start coordinates in `SequenceLocation` are meaningful for some `Allele` objects but not others. This is clearly unintended behavior.

## Proposed Solution 1a
One approach is to create an additional normalization condition (step 2) that if the start and end coordinate match, to set them both to a value of 0. This approach is straightforward, but the resulting message is nonsensical.

## Proposed Solution 1b
Same as 1a, but instead of setting to a value of 0, restore the interval to its original bounds. This allows for sensical messages, however leaves the choice of interval (start _and_ stop) meaningful for reference-matched `sequence` but not for reference-mismatched `sequence`.

## Proposed Solution 2
Before trim, store current interval bounds. Remove normalization step 2 (condition). When rolling left or right in normalization, you must roll to _at least_ those coordinates. This makes choice of interval meaningful for all sequences, except when needing to extend beyond the interval for full justification in repetitive regions. I believe this most closely matches the original intent of our normalization.

## Proposed Solution 3
Before trim, store current interval bounds. Append to normalization step 2 (condition) the additional constraint that if BOTH alleles are empty, to restore the interval bounds to their original state, no further normalization needed. This keeps intervals relevant only in the context of reference alleles, but makes it so both sides of the interval are relevant.

**All of these solutions are breaking changes** 😢.

**Comment by reece** [comment]
I'm not understanding the claimed problem. Let's agree on that there is a problem before declaring that we have a problem, especially a breaking one, which will make people nervous. **In fact, I think normalization is working perfectly.**

## Code for your scenarios

```
>>> from ga4gh.vr import normalize     

# Scenario 1                                                                                                                                                                                            
>>> normalize("AACTAA", interval=(0,6), alleles=[None, "AACTAA"])                                                                                                                                                                           
Traceback (most recent call last):
  File "<ipython-input-12-01a1b5a0b577>", line 1, in <module>
    normalize("AACTAA", interval=(0,6), alleles=[None, "AACTAA"])
  File "/home/reece/projects/ga4gh/vr-python/venv/3.7/lib/python3.7/site-packages/bioutils/normalize.py", line 97, in normalize
    raise ValueError("Must have at least two distinct alleles to normalize")
ValueError: Must have at least two distinct alleles to normalize

# Scenario 2                                                                                                                                                                                            
>>> normalize("AACTAA", interval=(1,6), alleles=[None, "ACTAA"])                                                                                                                                                                            
Traceback (most recent call last):
  File "<ipython-input-13-b0e17b0bdfd9>", line 1, in <module>
    normalize("AACTAA", interval=(1,6), alleles=[None, "ACTAA"])
  File "/home/reece/projects/ga4gh/vr-python/venv/3.7/lib/python3.7/site-packages/bioutils/normalize.py", line 97, in normalize
    raise ValueError("Must have at least two distinct alleles to normalize")
ValueError: Must have at least two distinct alleles to normalize

# Scenario 3                                                                                                                                                                                            
>>> normalize("AACTAA", interval=(0,6), alleles=[None, "ATCTAA"])                                                                                                                                                                           
((1, 2), ('A', 'T'))

# Scenario 4                                                                                                                                                                                            
>>> normalize("AACTAA", interval=(1,6), alleles=[None, "TCTAA"])                                                                                                                                                                            
((1, 2), ('A', 'T'))
```

## Discussion

VRS says that Alleles SHOULD be fully justified. These cases highlight why I though we can't strictly require normalization. Specifically, doing so would preclude us from representing states that we need to be able to represent.

There's nothing wrong with creating an Allele without normalization. In fact, this is necessary when one wants to refer to a (reference) span of sequence. (Rationale reminder: Although a Location itself would work for that concept, it's convenient for Allele to handle the ref agree case too so that that code that evaluates sequence at a location can always deal solely with Alleles. That is, the fact that it agrees with reference doesn't diminish the fact that it's an allele in the biological sense.)

Scenarios 1 and 2 are already addressed by the normalization implementation by requiring distinct alleles. So, if you want to talk about the span of reference sequence, go ahead as above. Normalization just doesn't make sense in this case. And, to be clear, the ids for the scenario 1 and 2 Alleles should NOT be identical because they refer to distinct spans of sequence.

For scenarios 3 and 4, I think normalization works entirely as desired: We collapse two degenerate alleles down to a single allele. Again, normalization isn't required here, so one is free to use an un-normalized form if that's important for the use case. And, of course, a single normalized allele should has only one identifier.

So, I think the normalization code is doing what we want. I think our logic is sound and consistent. I think the result is flexible for intended uses of Allele and normalization. And, I think the issues are entirely related to clarity and correctness of documentation, which definitely needs attention.

## Recommended Actions
- [ ] Although the code checks whether ref==alt as shown above, I now see that the pseudocode doesn't. In step 2, add text like "If both alleles are empty, the alleles are identical and refer to reference sequence. Normalization is not applicable."
- [ ] The computed identifier section says that implementations MUST normalize. This is an error and needs to be relaxed because, technically, it precludes generating a computed identifier for a reference Allele.

**Comment by ahwagner** [comment]
Thanks for this clarification, @reece. I did not realize that we intentionally disallowed reference allele normalization, and agree that we should clarify that in the specification. 

This is good news, as it means that we can safely add measures to compute reference IDs without worrying about breaking identification of existing reference alleles (since any such alleles are technically invalid already). We should probably add a reference allele to our test cases.

I disagree that we should relax the language around the requirement to normalize when addressing this, as I do not want to open the door to people inadvertently digesting non-normalized, non-reference alleles. Since we only pass sequence by reference and check the sequence content at normalization, we could reasonably handle this during normalization as a new step prepended to the algorithm:

> 1. **_Check for matching REF and ALT state:_  In the case of the match return an appropriate structure (_reference representation to be determined_), no further normalization needed.**
>
> 2. _Trimming:_ Remove prefix common to all alleles, if any, and...

**Comment by rrfreimuth** [comment]
> The computed identifier section says that implementations MUST normalize. This is an error and needs to be relaxed because, technically, it precludes generating a computed identifier for a reference Allele.

Thanks very much for clarifying that, @reece. I was operating with the understanding that normalization was mandatory, and therefore the described problem occurs.

I think @ahwagner 's approach of inserting a bit of logic in the normalization algorithm may be preferable to relaxing the language in the spec.  A discussion on this would be good.

I think we should be very intentional about our language.  As you both know, I consider "reference" to be a role that a sequence plays in a given use case, not an inherent attribute of the sequence itself.  A sequence used as reference in one use case may not be used as a reference in another.  Trio analysis and tumor:normal comparisons are examples of this.

Therefore, it is difficult to define a "reference sequence" or a "reference allele", when saying such entities do not need normalization.  I suggest that when the docs are updated we use phrases like "sequence used as reference" or "allele that matches the sequence used as reference".  I know it is more wordy, but I think the additional clarity is worth it.  It is too easy to assume "reference" = genome build (which then raises the question of "which build").

**Comment by ahwagner** [comment]
## Terminology Note
To address @rrfreimuth's comments above and for brevity, I'm going to refer to residues matching the sequence used as a reference as _concordant_ residues, and those not matching the sequence used as a reference as _discordant_ residues.

## Normalizing Reference Alleles
A thought I'd like to come back to here is how we address normalization for _all_ Alleles. Variant overprecision correction makes good sense to me, but there are cases where our correction algorithm has consequences that require special attention.

Specifically, truncation of concordant residue prefixes and suffixes requires us to handle additional logical cases, such as all-concordant sequence, or intended concordant-prefix / -suffix sequence. Designing mechanisms for addressing these cases are one possible direction, but an alternate one is requiring implementations to carefully choose interval bounds to explicitly describe the SequenceLocation they are describing, and only altering this SequenceLocation if the specified Allele is overprecise. 

I would like to further discuss Proposed Solution 2 [from the initial comment](https://github.com/ga4gh/vr-spec/issues/193#issue-608632582), as this proposal looks to make intervals meaningful for all Alleles, and allows for:
- concordant prefixes and suffixes to be maintained 
- consistency in representing representing all-concordant and partially-discordant sequence

The downside to this change would be that Allele computed identifiers generated with the v1.0 specification will not match the new identifiers in these cases.

**Comment by reece** [comment]
Summary of conversations among co-leads, mostly recorded in [these notes](https://docs.google.com/document/d/1PgMUNR2zErQpVvcfEr3zECy7hFDOSDQNkgQ_-LsqGIk/edit#):

Current issue:
* Any Allele can be digested, whether normalized or not
* The spec is unclear about how to normalize, and therefore how to digest, a reference allele. In https://vr-spec.readthedocs.io/en/1.0/impl-guide/normalization.html, 2. Condition, the ref Allele case is when both ref and alt are empty. Although vr-python handles this, the spec is unclear. Therefore, normalization of ref alleles is underspecified and appears to not even be applicable.

Proposal:
- [ ] Reserve the word "normalization" to mean the canonicalization process for all Variation classes.
- [ ] Require normalization prior to creating a computed identifier for all Variation classes.
- [ ] Modify current Allele normalization to handle ref agree, as follows: 
  - In *§2. Condition*, add "If the reference and alternate alleles are empty, return the input location and alleles."
- [ ] Make corresponding changes in vr-python

Importantly, the externally visible behavior in vr-python is unchanged. The above changes merely ensure that the spec does what's intended and that the reference implementation corresponds more closely to the outline implied in the spec.
