### ISSUE TITLE
amount of variants supported in a single message/document

### ISSUE THREAD

**Issue by priesgo** [ga4gh/vr-spec#25]
Depending on the use case we could think of using VMC to exchange just 1 variant (eg: beacon project), 10s/100s of variants (eg: prioritisation results), 1,000s of variants (eg: panel sequencing or even WES results) or 1,000,000s of variants (eg: WGS results).

There are two limiting factors: (1) size of the VMC payload and (2) computation time.

About (1) it would be great to have some estimates on the size of the payload related to the number of variants. What would be a reasonable payload size limit for a exchange message in an API as REST for instance?

About (2) the most time consuming processes may be right alignment and identifier computation. Could we have too some estimates on this respect?

**Comment by rrfreimuth** [comment]
These are important considerations, and we will have to address these questions at some point.

I’ve always been a little concerned that the VMC work conflates both the semantic modeling and the syntactic representation.  We may need to separate them just a bit so we can keep pushing the ball forward.

Thanks,
Bob

**Comment by reece** [comment]
Re @rrfreimuth's comment: The VMC spec is a long document precisely because it distinguishes semantics and syntax. We identified 4 contributions: Terminology, Conceptual Model, Spec (syntax), and Demos. For instance, see [this slide](https://docs.google.com/presentation/d/1HhQ_k-eEDPMrY0SR7wGGLrRgpQanqFuENIYbd69o8hQ/edit#slide=id.g25c5901bc7_0_192) from the 2017 GA4GH meeting. Perhaps we need to realign on that point.

Re @priesgo's comment: Frankly, we talked about creating specific use cases in the early days, but we ditched the effort because it was a rabbit hole unto itself. My desire would be for VMC to work at all volumes with a practical tradeoff between size efficiency, computational efficiency, and clarity. The biggest concern I have regarding efficiency is with the VMCBundle because it implies a potentially time- and space- expensive traversal of genotypes, haplotypes, alleles, and identifiers. However, there's nothing that requires using the bundle: I believe that adopting the rest of the models would still be a step forward. Furthermore, VMC encourages a sparse association of variation with observations and annotations, so it's likely to be more efficient than tabular forms and approximately as efficient as HGVS strings (which are generally less accurate).

Comments?

**Comment by reece** [comment]
VR focuses on breadth of expressiveness rather than efficiency. In principle, other techniques could be applied to reduce message size (e.g., msgpack), but that's not a focus of the spec currently.

In other words, messages will seem large. Our hope is that people also appreciate that they can express many kinds of variation.
