### ISSUE TITLE
Describe sequence hashing strategy

### ISSUE THREAD

**Issue by ahwagner** [ga4gh/vr-spec#58]
We need to describe our hashing strategy with a mind for future compatibility with refget, to enable implementations to move forward with the schema.

I believe that this is the intent of recent work on the seqrepo, and now the seqrepo REST API: https://github.com/biocommons/seqrepo-rest-service/issues/1

@reece your commentary here will be very helpful.

**Comment by reece** [comment]
There are three relevant functions to consider:
* Serializing an object
* Computing a digest on the serialized data
* Generating an identifier form the digest

The [Computed Identifiers section of the VMC spec]( https://docs.google.com/document/d/12E8WbQlvfZWk5NrxwLytmympPby6vsv60RxCeD5wc1E/edit#heading=h.k5dua9hh02tv) covers these topics.

For this issue, I imaging that the digest will be exactly the same: SHA512, trucated at 24 bytes, base64url encoded. This information content of this form and TRUNC512 is identical (both are 192 bits of data), but TRUNC512 uses 50% more space to do so. The seqrepo refget api implements this conversion already and can lookup sequences using TRUNC512 formats. 

We do need to finalized a decision about identifiers. See #32 for a discussion and continue that topic.

@ahwagner Please close if this answers your question.

**Comment by ahwagner** [comment]
Great, thanks @reece.

**Comment by ahwagner** [comment]
I'm reopening this issue. Now that we are considering a `ga4gh-digest` standard, I think we should have a discussion about what that will be. I think that the digest representation (hex vs. base64url) is a key component of that standard. We should pick one that is shared between refget and VR to give this decision more weight and solidarity between standards.

I have no strong preference for one encoding scheme or the other, only that they match.

@andrewyatz @reece comments?

**Comment by andrewyatz** [comment]
Refget choose the hex representation partly because of similarities with the existing md5 representation (partly as well the default encoding format from most checksum tools is hex) and that we felt the representation didn’t need to go into a storage layer. It could easily be stored in its natural binary format and then converted into a transmission format I.e. hex on the fly. 

That’s counter to the vr usecase where the extra space hex consumes versus other encodings does matter. Significantly. So I don’t overly mind how vr pins it’s colours to the mast on this. Base64 makes sense here and refget can adapt in future versions. 

What does worry me is we sidecar a Ga4gh wide standard for digests into this product. I don’t know if that will make it easier or harder to get it through PRC. We still need to get the refget designers to agree to this otherwise it runs the risk of splintering the effort.

Andy

**Comment by ahwagner** [comment]
Thank you, @andrewyatz. This is exactly the feedback I needed. I'm going to move ahead with extending the documentation in #71 describing our existing (base64url) encoding strategy.

I agree about the potential sidecar issue. I'm going to drop the notion of a GA4GH standard digest strategy from the documentation. If/when refget adopts the base64url representation, we can decide as a group if it is helpful / useful to push this as a GA4GH standard.
